language: go
dist: trusty

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x

env:
  matrix:
  - TARGET=amd64
  - TARGET=arm
  - TARGET=arm64
  - TARGET=ppc64le
  - TARGET=s390x

matrix:
  fast_finish: true

# Ubuntu 14.04 (trusty) doesn't have a new enough util-linux for nsenter,
# so we have to build it ourselves.
before_install:
 - wget https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.1.tar.gz -qO - | tar -xz -C .
 - sudo apt-get update
 - sudo apt-get install -y libncurses5-dev libslang2-dev gettext zlib1g-dev libselinux1-dev debhelper lsb-release pkg-config po-debconf autoconf automake autopoint libtool
 - pushd util-linux-2.24.1
 -   ./autogen.sh
 -   ./configure
 -   make
 -   sudo cp ./nsenter /usr/bin
 - popd
 - rm -rf util-linux-2.24.1

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/modocache/gover
 - go get github.com/mattn/goveralls
 - go get -t ./...

script:
 - make check

notifications:
  email: false

git:
  depth: 9999999
